--- #YAML:1.0
name:               WWW-Myspace-Data
version:            0.18
abstract:           WWW::Myspace database interaction
author:
    - Olaf Alders <olaf@wundersolutions.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Class::DBI:           0
    Class::DBI::AbstractSearch:  0
    Class::DBI::Loader:   0
    Class::Factory::Util:  1.3
    Config::General:      0
    Data::Dumper:         0
    DateTime:             0
    DateTime::Format::MySQL:  0
    Params::Validate:     0
    Test::More:           0
    WWW::Myspace:         0.88
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
